{
    "environment_setup": {
        "create_conda_env": {
            "stdout": "Collecting package metadata (repodata.json): ...working... done\nSolving environment: ...working... done\n\n## Package Plan ##\n\n  environment location: C:\\Users\\smith\\Anaconda3\\envs\\myenv\n\n  added / updated specs:\n    - python=3.8\n\n\nThe following NEW packages will be INSTALLED:\n\n  ca-certificates    pkgs/main/win-64::ca-certificates-2024.11.26-haa95532_0\n  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_1\n  openssl            pkgs/main/win-64::openssl-3.0.15-h827c3e9_0\n  pip                pkgs/main/win-64::pip-24.2-py38haa95532_0\n  python             pkgs/main/win-64::python-3.8.20-h8205438_0\n  setuptools         pkgs/main/win-64::setuptools-75.1.0-py38haa95532_0\n  sqlite             pkgs/main/win-64::sqlite-3.45.3-h2bbff1b_0\n  vc                 pkgs/main/win-64::vc-14.40-h2eaa2aa_1\n  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.40.33807-h98bb1dd_1\n  wheel              pkgs/main/win-64::wheel-0.44.0-py38haa95532_0\n\n\nPreparing transaction: ...working... done\nVerifying transaction: ...working... done\nExecuting transaction: ...working... done\n#\n# To activate this environment, use\n#\n#     $ conda activate myenv\n#\n# To deactivate an active environment, use\n#\n#     $ conda deactivate\n\n",
            "stderr": "\n\n==> WARNING: A newer version of conda exists. <==\n  current version: 4.8.2\n  latest version: 24.11.0\n\nPlease update conda by running\n\n    $ conda update -n base -c defaults conda\n\n\n",
            "returncode": 0
        },
        "activate_conda_env": {
            "stdout": "",
            "stderr": "",
            "returncode": 0
        },
        "pip_install": {
            "stdout": "Collecting pytest (from -r filtered_requirements.txt (line 1))\n\n  Using cached pytest-8.3.3-py3-none-any.whl.metadata (7.5 kB)\n\nCollecting flake8 (from -r filtered_requirements.txt (line 2))\n\n  Using cached flake8-7.1.1-py2.py3-none-any.whl.metadata (3.8 kB)\n\nCollecting iniconfig (from pytest->-r filtered_requirements.txt (line 1))\n\n  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)\n\nCollecting packaging (from pytest->-r filtered_requirements.txt (line 1))\n\n  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)\n\nCollecting pluggy<2,>=1.5 (from pytest->-r filtered_requirements.txt (line 1))\n\n  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)\n\nCollecting exceptiongroup>=1.0.0rc8 (from pytest->-r filtered_requirements.txt (line 1))\n\n  Using cached exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)\n\nCollecting tomli>=1 (from pytest->-r filtered_requirements.txt (line 1))\n\n  Using cached tomli-2.2.1-py3-none-any.whl.metadata (10 kB)\n\nCollecting colorama (from pytest->-r filtered_requirements.txt (line 1))\n\n  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)\n\nCollecting mccabe<0.8.0,>=0.7.0 (from flake8->-r filtered_requirements.txt (line 2))\n\n  Using cached mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)\n\nCollecting pycodestyle<2.13.0,>=2.12.0 (from flake8->-r filtered_requirements.txt (line 2))\n\n  Using cached pycodestyle-2.12.1-py2.py3-none-any.whl.metadata (4.5 kB)\n\nCollecting pyflakes<3.3.0,>=3.2.0 (from flake8->-r filtered_requirements.txt (line 2))\n\n  Using cached pyflakes-3.2.0-py2.py3-none-any.whl.metadata (3.5 kB)\n\nUsing cached pytest-8.3.3-py3-none-any.whl (342 kB)\n\nUsing cached flake8-7.1.1-py2.py3-none-any.whl (57 kB)\n\nUsing cached exceptiongroup-1.2.2-py3-none-any.whl (16 kB)\n\nUsing cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)\n\nUsing cached pluggy-1.5.0-py3-none-any.whl (20 kB)\n\nUsing cached pycodestyle-2.12.1-py2.py3-none-any.whl (31 kB)\n\nUsing cached pyflakes-3.2.0-py2.py3-none-any.whl (62 kB)\n\nUsing cached tomli-2.2.1-py3-none-any.whl (14 kB)\n\nUsing cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)\n\nUsing cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)\n\nUsing cached packaging-24.2-py3-none-any.whl (65 kB)\n\nInstalling collected packages: tomli, pyflakes, pycodestyle, pluggy, packaging, mccabe, iniconfig, exceptiongroup, colorama, pytest, flake8\n\nSuccessfully installed colorama-0.4.6 exceptiongroup-1.2.2 flake8-7.1.1 iniconfig-2.0.0 mccabe-0.7.0 packaging-24.2 pluggy-1.5.0 pycodestyle-2.12.1 pyflakes-3.2.0 pytest-8.3.3 tomli-2.2.1\n\n\n",
            "stderr": "",
            "returncode": 0
        },
        "additional_example.sh": [
            {
                "command": "python ../lice/core.py list-vars gpl3",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../lice/core.py', 'list-vars', 'gpl3']' command failed.  (See above for error)\npython: can't open file '../lice/core.py': [Errno 2] No such file or directory\n\n",
                    "returncode": 0
                }
            },
            {
                "command": "python ../lice/core.py custom-template ../lice/templates/template-custom.txt --year 2022 --org 'CustomOrg'",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../lice/core.py', 'custom-template', '../lice/templates/template-custom.txt', '--year', '2022', '--org', \"'CustomOrg'\"]' command failed.  (See above for error)\npython: can't open file '../lice/core.py': [Errno 2] No such file or directory\n\n",
                    "returncode": 0
                }
            }
        ],
        "example_usage.sh": [
            {
                "command": "python ../lice/core.py bsd3",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../lice/core.py', 'bsd3']' command failed.  (See above for error)\npython: can't open file '../lice/core.py': [Errno 2] No such file or directory\n\n",
                    "returncode": 0
                }
            },
            {
                "command": "python ../lice/core.py mit",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../lice/core.py', 'mit']' command failed.  (See above for error)\npython: can't open file '../lice/core.py': [Errno 2] No such file or directory\n\n",
                    "returncode": 0
                }
            },
            {
                "command": "python ../lice/core.py gpl3 --year 2021 --org 'ExampleOrg'",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../lice/core.py', 'gpl3', '--year', '2021', '--org', \"'ExampleOrg'\"]' command failed.  (See above for error)\npython: can't open file '../lice/core.py': [Errno 2] No such file or directory\n\n",
                    "returncode": 0
                }
            },
            {
                "command": "python ../lice/core.py apache --header --language py",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../lice/core.py', 'apache', '--header', '--language', 'py']' command failed.  (See above for error)\npython: can't open file '../lice/core.py': [Errno 2] No such file or directory\n\n",
                    "returncode": 0
                }
            },
            {
                "command": "python ../lice/core.py bsd2 --file LICENSE",
                "result": {
                    "stdout": "",
                    "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../lice/core.py', 'bsd2', '--file', 'LICENSE']' command failed.  (See above for error)\npython: can't open file '../lice/core.py': [Errno 2] No such file or directory\n\n",
                    "returncode": 0
                }
            }
        ]
    },
    "acceptance_tests": {
        "stdout": "",
        "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '-m', 'unittest', 'tests/acceptance/test_features.py']' command failed.  (See above for error)\nFFFFFF\n\n======================================================================\n\nFAIL: test_generate_apache_license_with_header (tests.acceptance.test_features.TestLiceFeatures)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\acceptance\\test_features.py\", line 29, in test_generate_apache_license_with_header\n\n    self.assertEqual(result.returncode, 0)\n\nAssertionError: 1 != 0\n\n\n\n======================================================================\n\nFAIL: test_generate_bsd2_license_to_file (tests.acceptance.test_features.TestLiceFeatures)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\acceptance\\test_features.py\", line 35, in test_generate_bsd2_license_to_file\n\n    self.assertEqual(result.returncode, 0)\n\nAssertionError: 1 != 0\n\n\n\n======================================================================\n\nFAIL: test_generate_bsd3_license (tests.acceptance.test_features.TestLiceFeatures)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\acceptance\\test_features.py\", line 14, in test_generate_bsd3_license\n\n    self.assertEqual(result.returncode, 0)\n\nAssertionError: 1 != 0\n\n\n\n======================================================================\n\nFAIL: test_generate_gpl3_license_with_year_and_org (tests.acceptance.test_features.TestLiceFeatures)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\acceptance\\test_features.py\", line 24, in test_generate_gpl3_license_with_year_and_org\n\n    self.assertEqual(result.returncode, 0)\n\nAssertionError: 1 != 0\n\n\n\n======================================================================\n\nFAIL: test_generate_mit_license (tests.acceptance.test_features.TestLiceFeatures)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\acceptance\\test_features.py\", line 19, in test_generate_mit_license\n\n    self.assertEqual(result.returncode, 0)\n\nAssertionError: 1 != 0\n\n\n\n======================================================================\n\nFAIL: test_list_template_vars (tests.acceptance.test_features.TestLiceFeatures)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\acceptance\\test_features.py\", line 43, in test_list_template_vars\n\n    self.assertEqual(result.returncode, 0)\n\nAssertionError: 1 != 0\n\n\n\n----------------------------------------------------------------------\n\nRan 6 tests in 0.228s\n\n\n\nFAILED (failures=6)\n\n\n",
        "returncode": 0
    },
    "unit_tests": {
        "run_tests": {
            "stdout": "",
            "stderr": "ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['coverage', 'run', '-m', 'unittest', 'tests/unit/test_module.py']' command failed.  (See above for error)\n.FFF...\n\n======================================================================\n\nFAIL: test_generate_license_with_custom_year_and_org (tests.unit.test_module.TestLice)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\unittest\\mock.py\", line 1191, in patched\n\n    return func(*args, **keywargs)\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\unit\\test_module.py\", line 23, in test_generate_license_with_custom_year_and_org\n\n    self.assertIn('2021 ExampleOrg', mock_stdout.getvalue())\n\nAssertionError: '2021 ExampleOrg' not found in <MagicMock name='stdout.getvalue()' id='2105231657056'>\n\n\n\n======================================================================\n\nFAIL: test_generate_license_with_defaults (tests.unit.test_module.TestLice)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\unittest\\mock.py\", line 1191, in patched\n\n    return func(*args, **keywargs)\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\unit\\test_module.py\", line 16, in test_generate_license_with_defaults\n\n    self.assertIn('2023 DefaultOrg', mock_stdout.getvalue())\n\nAssertionError: '2023 DefaultOrg' not found in <MagicMock name='stdout.getvalue()' id='2105232060488'>\n\n\n\n======================================================================\n\nFAIL: test_generate_license_with_header (tests.unit.test_module.TestLice)\n\n----------------------------------------------------------------------\n\nTraceback (most recent call last):\n\n  File \"c:\\users\\smith\\anaconda3\\lib\\unittest\\mock.py\", line 1191, in patched\n\n    return func(*args, **keywargs)\n\n  File \"C:\\Users\\smith\\code\\autoSWE\\system\\outputs\\v3\\lice\\tests\\unit\\test_module.py\", line 30, in test_generate_license_with_header\n\n    self.assertIn('# License Header for Python', mock_stdout.getvalue())\n\nAssertionError: '# License Header for Python' not found in <MagicMock name='stdout.getvalue()' id='2105232269888'>\n\n\n\n----------------------------------------------------------------------\n\nRan 7 tests in 0.028s\n\n\n\nFAILED (failures=3)\n\n\n",
            "returncode": 0
        },
        "coverage_report": {
            "stdout": "Name                        Stmts   Miss  Cover\n\n-----------------------------------------------\n\nlice\\core.py                   32      5    84%\n\nlice\\git_config.py              3      0   100%\n\nlice\\language_detector.py       7      5    29%\n\nlice\\license_header.py          7      3    57%\n\nlice\\license_template.py       15      0   100%\n\n-----------------------------------------------\n\nTOTAL                          64     13    80%\n\n\n",
            "stderr": "",
            "returncode": 0
        }
    }
}